#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

$dataitems=array();

$oak=new OAK;
$view=new stdClass;
if ($oak->get_view('menu/all',$view)===FALSE)
{
	print "Unable to get view\n";
}
else
{
	foreach ($view->rows as $row)
	{
		$menu=new OAKDocument('');
		if ($oak->get_document($row->id,$menu)===FALSE)
		{
			// print "Unable to get menu document\n";
		}
		else
		{
			// Get the GPS coordinates of the place
			$place_id=substr($menu->getID(),5);
			$place=new OAKDocument('');
			if ($oak->get_document($place_id,$place)===FALSE)
			{
				// print "Unable to get place document {$place_id}\n";
			}
			else
			{
				// Get the beers on their menu
				foreach ($menu->items as $item)
				{
					if ($item->type=='beer')
					{
						$dataitems[]=array(
							'lat' => $place->address->latitude,
							'lon' => $place->address->longitude,
							'place_id' => $place->getID(),
							'name' => $place->name,
							'beer_id' => $item->id,
						);
					}
				}
			}
		}
	}
}
// print_r($dataitems);exit;

// Sort them all by latitude
if (uasort($dataitems,'compare_lat'))
{
	// print_r($dataitems);exit;
	foreach ($dataitems as $dataitem)
	{
		print $dataitem['lat'].' '.$dataitem['lon'].' '.$dataitem['place_id'].' '.$dataitem['beer_id'].' '.json_encode(utf8_encode($dataitem['name']))."\n";
	}
}

function compare_lat($a,$b)
{
	$diff=((float)$a['lat']) - ((float)$b['lat']);
	if ($diff < 0)
		return -1;
	else if ($diff > 0)
		return 1;
	return 0;
}


?>