#!/usr/bin/php
<?php
require_once('beercrush/beercrush.php');

$rows=array();

$oak=new OAK;
$result=new OAKDocument('');

// Get Places
if ($oak->get_view("place/gps_coords",&$result)===false)
	throw new Exception('Unable to get view');
	
foreach ($result->rows as $row)
{
	$rows[]=$row;
}

// Get breweries
if ($oak->get_view("brewery/gps_coords",&$result)===false)
	throw new Exception('Unable to get view');

foreach ($result->rows as $row)
{
	$rows[]=$row;
}

// Sort them all by latitude
if (uasort($rows,'compare_lat'))
{
	foreach ($rows as $row)
	{
		// Get placetype for the place
		$doc=BeerCrush::api_doc($oak,BeerCrush::docid_to_docurl($row->id));

		print $row->value->lat."\t".$row->value->lon."\t".$row->id."\t".trim(json_encode($row->key),'"')."\t".$doc->placetype."\n";
	}
}

function compare_lat($a,$b)
{
	$diff=((float)$a->value->lat) - ((float)$b->value->lat);
	if ($diff < 0)
		return -1;
	else if ($diff > 0)
		return 1;
	return 0;
}

?>