#!/bin/bash


function usage() {
	cat -<<EOF
${0##*/} -C <config>

EOF
	exit;
}

while getopts "C:" opt; do
	case $opt in
		C )
			conf_file=$OPTARG;
			;;
		\? )
			usage;
			;;
	esac
done

if [ -z "$conf_file" ]; then
	usage;
fi

OAKConfig=$conf_file /usr/local/beercrush/bin/latlonfile > /var/local/BeerCrush/meta/latlonpairs.txt;
OAKConfig=$conf_file /usr/local/beercrush/bin/beers > /var/local/BeerCrush/meta/nearby_beer.txt;
/usr/local/beercrush/bin/locations_gps_data -C $conf_file > /var/local/BeerCrush/meta/nearby_locations.txt;
