#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

$oak=new OAK;
$breweries=new OAKDocument('');
$oak->get_view("/brewery/all",&$breweries);

$xmlwriter=new XMLWriter;
$xmlwriter->openMemory();
$xmlwriter->startDocument();
$xmlwriter->startElement('breweries');

$last_letter=null;

foreach ($breweries->rows as $row)
{
	$brewery=new OAKDocument('');
	$oak->get_document($row->id,&$brewery);
	
	$letter=strtoupper(substr(trim($brewery->name),0,1));
	if ('A'<=$letter && $letter<='Z') {}
	else
		$letter="#";
		
	if ($last_letter!=$letter) // A new alphabetic section?
	{
		if (!is_null($last_letter)) // End the last alphabetic section
			$xmlwriter->endElement();
		$xmlwriter->startElement('group');
		$xmlwriter->writeAttribute('title',$letter);
		$last_letter=$letter;
	}
	
	$xmlwriter->startElement('brewery');
	$xmlwriter->writeAttribute('id',$brewery->getID());
	$xmlwriter->writeElement('name',$brewery->name);
	$xmlwriter->endElement();
}

$xmlwriter->endDocument();
print $xmlwriter->outputMemory();

?>