#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

$oak=new OAK;
$breweries=new OAKDocument('');
$oak->get_view("brewery/all",&$breweries);

$output=new stdClass;

foreach ($breweries->rows as $row)
{
	$brewery=new OAKDocument('');
	$oak->get_document($row->id,&$brewery);
	
	$letter=strtoupper(substr(trim($brewery->name),0,1));
	if ('A'<=$letter && $letter<='Z') {}
	else
		$letter="#";
		
	if (!isset($output->$letter))
		$output->$letter=array();

	$brewery_info=array(
		'id' => $brewery->getID(),
		'name' => $brewery->name,
	);
	array_push($output->$letter,$brewery_info);
}

print json_encode($output);

?>