#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

if [ -z "$1" ]; then
	echo "Usage: $0 <Brewery ID>";
	exit;
fi

# Get list of beers for brewery
$APP_DIR/scripts/brewery/beerlist "$1" |
	$APP_DIR/tools/updatedoc "meta:$1" beerlist "brewery_meta" | 
	$APP_DIR/tools/putdoc "meta:$1"

echo Updated meta:$1;
