#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

function process () {
	# Update beer meta info doc
	# $APP_DIR/scripts/beer/meta "$1"

	PATHNAME=`echo $1 | cut -d ':' -f 1,2 | sed -e 's/:/\//g'`;
	BEERNAME=`echo $1 | cut -d ':' -f 3`;

	# Update beer XML doc
	if [ ! -d $WWW_DIR/xml/$PATHNAME ]; then
		mkdir -p $WWW_DIR/xml/$PATHNAME;
	fi
	$APP_DIR/tools/getdoc "$1" | $APP_DIR/tools/json2xml > $WWW_DIR/xml/$PATHNAME/$BEERNAME.xml
	echo xml/$PATHNAME/$BEERNAME.xml
	
	# Update beerlist for the brewery
	BREWERY_ID=`$APP_DIR/tools/getdoc "$1" | tools/json2xml | xmlstarlet sel -t -m '/beer' -v '@brewery_id'`;
	$APP_DIR/src/onchange/brewery "$BREWERY_ID"

	# Update beer page
	# cat $WWW_DIR/xml/$FILENAME.xml | $APP_DIR/tools/xslt $APP_DIR/xsl/beer/beer.xsl > $WWW_DIR/html/$FILENAME.html
	# echo > $WWW_DIR/html/$FILENAME.html
}

# echo "$1 changed";
if [ -z "$1" ]; then
	# *All* beer docs changed!
	$APP_DIR/tools/getdoc "/_view/beer/all" | $APP_DIR/tools/json2xml  | xmlstarlet sel -t -m "/doc/rows/item" -v id -n | sed -e '/^$/d' |
	while read BEER_ID; do
		process $BEER_ID;
	done
else
	process $1;
fi

