#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

function process () {
	# Update beer meta info doc
	# $APP_DIR/scripts/beer/meta "$1"

	PATHNAME=`echo $1 | cut -d ':' -f 1,2 | sed -e 's/:/\//g'`;
	BEERNAME=`echo $1 | cut -d ':' -f 3`;

	# Update beer JSON doc
	if [ ! -d $WWW_DIR/json/$PATHNAME ]; then
		mkdir -p $WWW_DIR/json/$PATHNAME;
	fi
	$APP_DIR/tools/getdoc "$1" > $WWW_DIR/json/$PATHNAME/$BEERNAME.json
	echo json/$PATHNAME/$BEERNAME.json
	
	# Update beerlist for the brewery
	BREWERY_ID=`cat $WWW_DIR/json/$PATHNAME/$BEERNAME.json | php -r '$s=file_get_contents("php://stdin");$o=json_decode($s);$a="@attributes";print $o->$a->brewery_id;'`;
	BREWERY_PATHNAME=`echo $BREWERY_ID | sed -e 's/:/\//'`;
	if [ ! -d $WWW_DIR/json/$BREWERY_PATHNAME/ ]; then
		mkdir -p $WWW_DIR/json/$BREWERY_PATHNAME/;
	fi
	$APP_DIR/scripts/brewery/beerlist $BREWERY_ID > $WWW_DIR/json/$BREWERY_PATHNAME/beerlist.json

	# Update beer page
	# cat $WWW_DIR/xml/$FILENAME.xml | $APP_DIR/tools/xslt $APP_DIR/xsl/beer/beer.xsl > $WWW_DIR/html/$FILENAME.html
	# echo > $WWW_DIR/html/$FILENAME.html
}

# echo "$1 changed";
if [ -z "$1" ]; then
	# *All* beer docs changed!
	$APP_DIR/tools/getview "beer/all" | $APP_DIR/tools/json2xml  | xmlstarlet sel -t -m "/doc/rows/item" -v id -n | sed -e '/^$/d' |
	while read BEER_ID; do
		process $BEER_ID;
	done
else
	process $1;
fi

