#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

# echo "$1 changed";
if [ -z "$1" ]; then
	echo "Usage: $0 <Beer Review ID>";
	exit;
fi

# Update beer meta info doc
# $APP_DIR/scripts/beer/meta "$1"

BREWERY_ID=`echo "$1" | cut -d ':' -f 2`;
BEER_ID=`echo "$1" | cut -d ':' -f 3`;
USER_ID=`echo "$1" | cut -d ':' -f 4`;

# TODO: if BREWERY_ID, BEER_ID or USER_ID are empty strings, fail with an error

XMLFILE_DIR="$WWW_DIR/xml/beer_review/$BREWERY_ID/$BEER_ID";

# Update beer review XML doc
if [ ! -d $XMLFILE_DIR ]; then
	mkdir -p $XMLFILE_DIR;
fi

$APP_DIR/tools/getdoc "$1" | $APP_DIR/tools/json2xml > $XMLFILE_DIR/$USER_ID.xml

echo $XMLFILE_DIR/$USER_ID.xml

# Update beer review page
# cat $WWW_DIR/xml/beer/$1.xml | $APP_DIR/tools/xslt $APP_DIR/xsl/beer/beer.xsl > $WWW_DIR/html/beer/$1.html

#
# Update user's beer reviews XML doc
#
if [ ! -d $WWW_DIR/xml/user/$USER_ID ]; then
	mkdir -p "$WWW_DIR/xml/user/$USER_ID";
fi

$APP_DIR/tools/getdoc "/_view/beer_reviews/by_user?key=%22$USER_ID%22" |
$APP_DIR/tools/json2xml | 
xmlstarlet sel -t -m '//doc/rows/item' -v id -n |
sed -e '/^ *$/d' |
while read REVIEW_ID; do
	REVIEW_XML_FILE="$WWW_DIR/xml/"`echo $REVIEW_ID | sed -e 's/:/\//g'`".xml";
	BEER_ID=`xmlstarlet sel -t -m "/beer_review" -v beer_id "$REVIEW_XML_FILE"`;
	BEER_XML_FILE=$WWW_DIR/xml/beer/$BEER_ID.xml;
	BEER_NAME=`xmlstarlet sel -t -m "/beer" -v name $BEER_XML_FILE`;
	
	cat "$REVIEW_XML_FILE" |
		xmlstarlet ed --omit-decl --subnode /beer_review -t elem -n beer -v "" | 
		xmlstarlet ed --omit-decl --subnode /beer_review/beer -t elem -n name -v "$BEER_NAME"
done |
sed -e '1i\<beer_reviews>' -e '$a\</beer_reviews>' |
xmlstarlet fo > $WWW_DIR/xml/user/$USER_ID/beer_reviews.xml

echo $WWW_DIR/xml/user/$USER_ID/beer_reviews.xml

#
# Update the doc listing all the reviews for this beer
#
$APP_DIR/tools/getdoc "_view/beer_reviews/for_beer?key=%22$BREWERY_ID:$BEER_ID%22" | 
$APP_DIR/tools/json2xml | 
xmlstarlet sel -t -m '//doc/rows/item' -v id -n |
sed -e '/^ *$/d' |
while read REVIEW_ID; do
	REVIEW_XML_FILE="$WWW_DIR/xml/"`echo $REVIEW_ID | sed -e 's/:/\//g'`".xml";
	xmlstarlet fo --omit-decl $REVIEW_XML_FILE;
done | 
sed -e '1i\<beer_reviews>' -e '$a\</beer_reviews>' |
xmlstarlet fo > $WWW_DIR/xml/beer_review/$BREWERY_ID/$BEER_ID/_all.xml

echo $WWW_DIR/xml/beer_review/$BREWERY_ID/$BEER_ID/_all.xml
