#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

function process () {
	TYPE=`echo $1|cut -d ':' -f 1`;
	if [ "$TYPE" != "brewery" ]; then
		exit;
	fi
	BREWERY=`echo $1|cut -d ':' -f 2`;
	FILENAME=`echo $1 | sed -e 's/:/\//'`;

	# Update the brewery page in JSON
	$APP_DIR/tools/getdoc "$1" > $WWW_DIR/json/$FILENAME.json
	echo json/$FILENAME.json

	# Update brewery XML doc
	cat $WWW_DIR/json/$FILENAME.json | $APP_DIR/tools/json2xml > $WWW_DIR/xml/$FILENAME.xml
	# TODO: handle failure to create the file and log it
	echo xml/$FILENAME.xml

	# Update brewery HTML page
	cat $WWW_DIR/xml/$FILENAME.xml | $APP_DIR/tools/xslt $APP_DIR/xsl/brewery/brewery.xsl > $WWW_DIR/html/$FILENAME.html
	# TODO: handle failure to create the file and log it
	echo html/$FILENAME.html
	
}

# Always refresh the list of breweries XML doc (their name may have changed)
$APP_DIR/scripts/brewery/brewery_list > $WWW_DIR/json/breweries.json

# echo "$1 changed";
if [ -z "$1" ]; then
	# *All* brewery docs changed!
	$APP_DIR/tools/getview "brewery/all" | $APP_DIR/tools/json2xml  | xmlstarlet sel -t -m "/doc/rows/item" -v id -n | sed -e '/^$/d' |
	while read BREWERY_ID; do
		process $BREWERY_ID;
	done
else
	process $1;
fi

