#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

$oak=new OAK;

if ($argc<2)
{
	$all_menus=new OAKDocument('');
	if ($oak->get_view('menu/all',&$all_menus)===false)
		throw new Exception('Unable to get all menus');
		
	foreach ($all_menus->rows as $row)
	{
		process($row->id,$oak);
	}
}
else
{
	process($argv[1],$oak);
}

function process($id,$oak)
{
	// Add in the beer/name element to the item element
	$menu=new OAKDocument('');
	if ($oak->get_document($id,$menu)===false)
		throw new Exception('Unable to get document '.$id);

	$attribs="@attributes";
	foreach ($menu->items as $item)
	{
		$itemdoc=new OAKDocument('');
		if ($oak->get_document($item->$attribs->id,&$itemdoc)===false)
			throw new Exception('Unable to get document '.$item->id);
		
		$item->name=$itemdoc->name;
	}
}

?>