#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

function process_place($place_id)
{
	global $oak;
	
	$doc=new OAKDocument('');
	if ($oak->get_document($place_id,$doc)!==TRUE)
	{
	}
	else
	{
		// If it doesn't have GPS coordinates...
		if (empty($doc->address->latitude) || empty($doc->address->longitude))
		{
			// Run geoloc to get the GPS coordinates
			exec($oak->get_file_location('APP_DIR').'/tools/geoloc '.$place_id);
		}
	}
}

$oak=new OAK;

if (empty($argv[1]))
{
	$places=new stdClass;
	if ($oak->get_view('place/all',$places)!==TRUE)
	{
		
	}
	else
	{
		foreach ($places->rows as $row)
		{
			print $row->id."\n";
			process_place($row->id);
		}
	}
}
else
{
	process_place($argv[1]);
}

?>
