#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

$oak=new OAK;

if ($argc<2)
{
	$all_reviews=new OAKDocument('');
	if ($oak->get_view('review/all',&$all_reviews)===false)
		throw new Exception('Unable to get all reviews');
		
	foreach ($all_reviews->rows as $row)
	{
		process($row->id,$oak);
	}
}
else
{
	process($argv[1],$oak);
}

function process($id,$oak)
{
	/*
		Review IDs are of the form:

			review:<doc id>:<user_id>

		where <doc id> is the ID of the document being reviewed (which may contain subparts) and <user_id> is the user who is doing the review.
	*/

	if (strncmp($id,'review:',7))
	{
		$oak->log("$id is not a review\n");
		return;
	}
	
	$review=new OAKDocument('');
	if ($oak->get_document($id,$review)!==true)
	{
		$oak->log('Unable to get review document:'.$id);
	}
	else
	{
		$parts=preg_split('/:/',$id);

		switch ($parts[1])
		{
			case "place":
				break;
			case "beer":
				$oak->log("Purging beer doc");
				// Uncache the doc for the beer
				$beer_id=$parts[1].':'.$parts[2].':'.$parts[3];
				$oak->purge_document_cache('app','/api/beer/view?beer_id='.$beer_id);
				// Uncache the view document for this beer
				$oak->purge_document_cache('couchdb','/_design/beer_reviews/_view/for_beer?key=%22'.$beer_id.'%22');
				break;
			default:
				$oak->log('Unrecognized review type: '.$parts[1]);
				break;
		}
	}
}

?>