#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');
require_once('OAK/solr.class.php');

$opts=getopt('C:h');

if (isset($opts['h']) || empty($opts['C'])) {
	$cmdname=basename($argv[0]);
	print <<<EOF
Usage: $cmdname -C <conf file>

	-C Specify path to .conf file


EOF;
	exit(2);
}

$docid=$argv[3];

try {
	$oak=new OAK($opts['C']);
}
catch (Exception $x) {
	print $x->getMessage()."\n";
	exit;
}

$schema=json_decode(file_get_contents(dirname($opts['C'])."/schema.json"));
$solridx=new OAKSolrIndexer($oak,$schema);

$total_docs_added=0;

if (empty($docid)) {
	// Update ALL docs
	add_all_docs('beer/all');
	add_all_docs('brewery/all');
	add_all_docs('place/all');
	
	$solridx->optimize();
}
else
{
	$doc=new OAKDocument('');
	$oak->get_document($docid,$doc);
	$solridx->index_doc($doc);
}

function add_all_docs($view,$max=100)
{
	global $oak;
	global $solridx;
	
	$startkey="";
	$startkey_docid="";
	$count=0;

	do
	{
		$alldocs=new stdClass;
		/*
		We have to use startkey, startkey_docid and skip to propertly paginate through all documents without repeating any docs.
		The skip value is 0 the first time through since we don't want to skip the 1st document, but it's 1 every other loop
		iteration because, without it, the first document would be the last document from the previous iteration.
		*/
		$oak->get_view($view.'?limit='.$max.'&startkey='.urlencode('"'.$startkey.'"').'&startkey_docid='.$startkey_docid.'&skip='.($count?1:0),$alldocs);
		
		$xmlwriter=$solridx->batch_index_doc_start();

		foreach ($alldocs->rows as $row)
		{
			$startkey=$row->key;
			$startkey_docid=$row->id;
		
			$doc=new OAKDocument('');
			$oak->get_document($row->id,$doc);
			$solridx->batch_index_doc($doc,$xmlwriter);
			
			++$count;
		}
		
		$solridx->batch_index_doc_end($xmlwriter);
	
		if (count($alldocs->rows)<$max)
			$startkey=null; // We're done!

		$pct=(int)(($count/$alldocs->total_rows)*100);
		print "$view: $count/{$alldocs->total_rows} documents ($pct%)\n";
	}
	while (!is_null($startkey));
	
}

?>