.PHONY: SAFETY_CHECK ROOT_SAFETY_CHECK ALL clean install check setup build local_install
.DEFAULT: ALL
	
TOPDIR := $(dir $(lastword $(MAKEFILE_LIST)))
	
SHELL = /bin/bash

# Get necessary BeerCrush config settings
WWW_DIR:=$(shell php -r '$$cfg=json_decode(file_get_contents("/etc/BeerCrush/webapp.conf"));print $$cfg->file_locations->WWW_DIR."\n";')
BC_BIN_DIR:=/usr/local/beercrush/bin
	
ALL:
	@bash $(TOPDIR)make_recursively.sh build
	
# Verifies that we're ready to go
SAFETY_CHECK:
	@if [ $(shell whoami) = "root" ]; then echo "Must NOT be root for install"; exit 1; fi
	@if [ -z "$(WWW_DIR)" ]; then \
		echo "WWW_DIR is blank"; \
		exit 1; \
	fi

install: SAFETY_CHECK
	@bash $(TOPDIR)install_recursively.sh

check:
	@bash $(TOPDIR)make_recursively.sh local_check

local_check:
	if [ -f check.sh ]; then bash check.sh; fi
