#!/bin/bash

BEERCRUSH_WWW_DIR="/var/www/BeerCrush/"
BEERCRUSH_ETC_DIR="/etc/BeerCrush/"
BEERCRUSH_PHPINC_DIR="/usr/share/php/beercrush/"
BEERCRUSH_SOURCE_DIR="$HOME/beercrush/"
BEERCRUSH_LOCALDATA_DIR="/var/local/BeerCrush/"

BEERCRUSH_APPSERVER_USER=www-data

function USAGE()
{
	echo "Usage: $0 <appserver|wwwproxy|couchdbproxy|solrproxy|couchdb|solr|memcacheq|mgmt> <mgmt server>";
}

if [ -z "$1" -o -z "$2" ]; then
	USAGE;
	exit;
fi

# TODO: verify that I'm root or have sudo privileges

if [ ! -f $BEERCRUSH_ETC_DIR/setup.conf ]; then
	if [ $1 == "mgmt" ]; then
		echo "$BEERCRUSH_ETC_DIR/setup.conf doesn't exist but must exist on the mgmt server. Please create it.";
	else
		# Retrieve setup.conf from mgmt server
		rsync $2:$BEERCRUSH_ETC_DIR/setup.conf $BEERCRUSH_ETC_DIR/setup.conf;
	fi
	exit;
fi

if ! ping -q -c 1 -W 3 -w 3 $2 &> /dev/null; then
	echo "$2 doesn't seem to be reachable on the network. Is the name or IP address correct?";
	exit;
fi

. $BEERCRUSH_ETC_DIR/setup.conf;


#
# Common setup tasks
#
sudo apt-get --quiet --quiet install rsync=3.0.6-1 ntpdate=1:4.2.4p6+dfsg-2

# Set date/time
sudo ntpdate-debian > /dev/null;

#
# Node-dependent setup tasks
#
case $1 in
	couchdb)
		echo "Setting up database server...";
		sudo apt-get --quiet --quiet install couchdb=0.9.0-2+b1
		
		# Make sure bind_address is set to 0.0.0.0 in /etc/couchdb/local.ini
		if ! sudo grep -e "^ *bind_address *= *0.0.0.0 *$" /etc/couchdb/local.ini > /dev/null; then
			echo "Fixing bind_address in /etc/couchdb/local.ini (backing up current to /etc/couchdb/local.ini.old)";
			sudo sed --in-place=.old -e 's/^ *; *bind_address *= *[0-9\.][0-9\.]*/bind_address=0.0.0.0/' /etc/couchdb/local.ini;
			echo "Restarting CouchDB";
			sudo /etc/init.d/couchdb restart;
		fi
		
		# Check if beercrush database exists
		if [ `curl --silent  -D -  http://localhost:5984/beercrush | head -1 | awk '{print $2}'` != "200" ]; then
			echo "beercrush db doesn't exist. You'll need to copy one from somewhere.";
			exit;
		fi

		# TODO: setup replication between this server and another
		# TODO: update design docs from src/db/designdocs.json
		# TODO: setup snapshots of db
		
		;;
		
	solr)
		echo "Setting up Solr...";
		sudo apt-get --quiet --quiet install solr-tomcat6=1.3.0+ds1-1 tomcat6-admin=6.0.20-7
		# TODO: verify /etc/tomcat6/tomcat-users.xml is correct
		# TODO: copy the BeerCrush conf/solr/schema.xml to /etc/solr/conf/schema.xml
		# TODO: copy the BeerCrush conf/solr/solrconfig.xml to /etc/solr/conf/solrconfig.xml
		# TODO: attempt a Solr query to prove it works
		;;
	memcacheq)
		echo "Setting up memcacheq server...";
		# See http://memcachedb.org/memcacheq/INSTALL.html
		sudo apt-get --quiet --quiet install libdb4.8=4.8.24-1 libdb4.8-dev=4.8.24-1 libevent-1.4-2=1.4.12-stable-1 libevent-dev=1.4.12-stable-1;
		
		# Install MemcacheQ:
		curl http://troyandgay.com/memcacheq_0.1.1-1_i386.deb > $HOME/memcacheq_0.1.1-1_i386.deb
		dpkg -i $HOME/memcacheq_0.1.1-1_i386.deb
		# 	curl --silent http://memcacheq.googlecode.com/files/memcacheq-0.1.1.tar.gz > $HOME/memcacheq-0.1.1.tar.gz
		# 	cd $HOME; tar xvzf memcacheq-0.1.1.tar.gz; cd memcacheq-0.1.1
		#	./configure --enable-threads
		#	make
		#	sudo make install
		
		# Make sure memcacheq is running
		# If not, start memcacheq:
		memcacheq -d -r -H /var/lib/memcacheq -N -v -L 1024 -B 1024 > /var/log/memcacheq.log 2>&1
		;;
	mgmt)
		echo "Setting up management server...";

		sudo apt-get --quiet --quiet install subversion=1.6.3dfsg-1 supervisor=3.0a7-2.1

		if [ ! -d $BEERCRUSH_SOURCE_DIR ]; then
			# Get code from Subversion
			svn co $SUBVERSION_URL $BEERCRUSH_SOURCE_DIR
		else
			# Get the latest version
			svn update $BEERCRUSH_SOURCE_DIR
		fi

		# TODO: kill update_doc, if running, and start new process
		
		;;
	app)
		echo "Setting up app server...";

		sudo apt-get --quiet --quiet install apache2=2.2.14-2 libapache2-mod-rpaf=0.5-3 \
			php5=5.2.11.dfsg.1-1 php5-cli=5.2.11.dfsg.1-1 php5-cgi=5.2.11.dfsg.1-1 \
			php5-dev=5.2.11.dfsg.1-1 php5-curl=5.2.11.dfsg.1-1 php5-imagick=2.1.1RC1-1+b1 \
			php5-uuid=1.5.1-1.1+b1 php5-memcached=1.0.0-1 php-apc=3.0.19-2 \
			supervisor=3.0a7-2.1 \
			spread=3.17.4-2+b1 libspread1-dev=3.17.4-2+b1 \
			libfcgi-dev=2.4.0-7 \
			libcurl4-openssl-dev=7.19.7-1 \
			xmlstarlet=1.0.1-2 \
			subversion=1.6.3dfsg-1 

		if [ ! -f $BEERCRUSH_ETC_DIR/webapp.conf ]; then
			echo "$BEERCRUSH_ETC_DIR/webapp.conf doesn't exist. You can get a sample from svn://beercrush/conf/appserver/webapp.conf.";
			exit;
		fi

		for DIR in $BEERCRUSH_WWW_DIR $BEERCRUSH_ETC_DIR $BEERCRUSH_LOCALDATA_DIR $BEERCRUSH_PHPINC_DIR /var/run/BeerCrush $BEERCRUSH_WWW_DIR/uploads $BEERCRUSH_SOURCE_DIR/src /var/local/BeerCrush/meta/; do
			if [ ! -d $DIR ]; then
				sudo mkdir -p $DIR;
			fi
		done
		
		sudo chown -R $BEERCRUSH_APPSERVER_USER.$BEERCRUSH_APPSERVER_USER /var/local/BeerCrush/;
		
		# Copy the src tree so we can build anything that is needed
		echo "Copying from $MGMT_SERVER...";
		rsync --recursive --delete $MGMT_SERVER:$BEERCRUSH_SOURCE_DIR/src/ $BEERCRUSH_SOURCE_DIR/src/
		# Run make in source tree
		make -C $BEERCRUSH_SOURCE_DIR/src/ clean
		make -C $BEERCRUSH_SOURCE_DIR
		sudo make -C $BEERCRUSH_SOURCE_DIR install
		
		# TODO: configure syslog.conf for OAK logging
		# TODO: config logrotate for /var/log/oak.log
		# TODO: install and setup PHP's APC (opcode cache)
		# TODO: make autocompletenames.txt and latlonpairs.txt in /var/local/BeerCrush/meta
		# TODO: build fcgi binaries
		# TODO: Config PHP FastCGI
		# TODO: turn off PHP's magic quotes
		# TODO: make sure PHP's include_path is correct and uncommented in php.ini

		# TODO: verify that the OAK.conf file is correct
		
		# TODO: make this work:
		# sudo pecl install spread
		
		# TODO: install libmemcached 0.28+
		# TODO: pecl install memcached
		# TODO: make sure permissions are correct for $BEERCRUSH_WWW_DIR and subdirs (beercrush group?)

		###############################################
		# Apache 2.2
		###############################################
		
		if [ ! -f /etc/apache2/sites-enabled/BeerCrush ]; then
			echo "You must create /etc/apache2/sites-available/BeerCrush and then create a symlink in /etc/apache2/sites-enabled.";
			echo "You can get one from svn://beercrush/conf/apache/appserver.conf and then run 'a2ensite BeerCrush'.";
			exit;
		fi
		
		# Verify that the ServerName param is correct
		if [ `grep ServerName /etc/apache2/sites-enabled/BeerCrush |awk '{print $2}'` != $APACHE_SERVER_NAME ]; then
			echo "/etc/apache2/sites-enabled/BeerCrush: ServerName is not $APACHE_SERVER_NAME";
			exit;
		fi
		
		# Verify that Apache is listening on port 8008
		if ! grep "^ *Listen 8008 *$" /etc/apache2/ports.conf; then
			echo "/etc/apache2/ports.conf: Needs a Listen 8008 line";
			exit;
		fi
		

		###############################################
		# Supervisord
		###############################################

		# Verify that supervisord is config'd
		if [ ! -f /etc/supervisor/conf.d/BeerCrush-app.conf ]; then
			echo "I don't see /etc/supervisor/conf.d/BeerCrush-app.conf. You can get one from svn://beercrush/conf/supervisord/appserver.conf."
			exit;
		fi
		
		# Verify that /var/run/supervisor exists
		if [ ! -d /var/run/supervisor ]; then
			echo "Creating /var/run/supervisor";
			sudo mkdir /var/run/supervisor
		fi

		# Tell supervisord to restart FCGI programs
		echo "Restarting Supervisord...";
		sudo /etc/init.d/supervisor stop;
		sudo /etc/init.d/supervisor start;
		# sudo supervisorctl restart autocomplete: nearby: nearby_beer:;
		
		sudo /etc/init.d/apache2 restart;
		
		;;
		
	wwwproxy)
		echo "Setting up www proxy server...";
		
		sudo apt-get --quiet --quiet install nginx=0.7.63-1
		
		if [ ! -f /etc/nginx/sites-enabled/BeerCrush-www ]; then
			echo "You must create /etc/nginx/sites-available/BeerCrush-www and then create a symlink in /etc/nginx/sites-enabled.";
			echo "You can get one from svn://beercrush/conf/nginx/wwwserver.conf.";
			exit;
		fi
		
		sudo /etc/init.d/nginx restart;
		
		;;
		
	couchdbproxy)
		echo "Setting up CouchDB proxy server...";
	
		sudo apt-get --quiet --quiet install nginx=0.7.63-1

		if [ ! -f /etc/nginx/sites-enabled/couchdb ]; then
			echo "You must create /etc/nginx/sites-available/couchdb and then create a symlink in /etc/nginx/sites-enabled";
			echo "You can get one from svn://beercrush/conf/nginx/couchdb.conf.";
			exit;
		fi
		
		if [ ! -d /var/local/nginx-couchdb/ ]; then
			sudo mkdir /var/local/nginx-couchdb/;
			sudo chown www-data.www-data /var/local/nginx-couchdb/;
		fi
		
		# TODO: Verify that server_name is correct in /etc/nginx/sites-enabled/couchdb
		# Test the config
		if ! sudo /etc/init.d/nginx configtest; then
			echo "Please fix NGiNX config errors above.";
			exit;
		fi

		sudo /etc/init.d/nginx restart;
		
		# Test that the proxy works
		if [ `curl --silent  -D  -  http://localhost:7000/beercrush/ |head -n 1 | awk '{print $2}'` != "200" ]; then
			echo "Unable to access couchdb through proxy (http://localhost:7000/beercrush/)";
			exit;
		fi

		;;
		
	solrproxy)
		echo "Setting up Solr proxy server...";
	
		sudo apt-get --quiet --quiet install nginx=0.7.63-1

		if [ ! -f /etc/nginx/sites-enabled/solr ]; then
			echo "You must create /etc/nginx/sites-available/solr and then create a symlink in /etc/nginx/sites-enabled";
			echo "You can get one from svn://beercrush/conf/nginx/solr.conf.";
			exit;
		fi

		if [ ! -d /var/local/nginx-solr/ ]; then
			sudo mkdir /var/local/nginx-solr/;
			sudo chown www-data.www-data /var/local/nginx-solr/;
		fi
		
		# Test the config
		if ! sudo /etc/init.d/nginx configtest; then
			echo "Please fix NGiNX config errors above.";
			exit;
		fi
		
		sudo /etc/init.d/nginx restart;
		
		# Test that the proxy works
		if [ `curl --silent  -D  -  http://localhost:7007/solr/ |head -n 1 | awk '{print $2}'` != "200" ]; then
			echo "Unable to access Solr through proxy (http://localhost:7007/solr/)";
			exit;
		fi
		
		;;
		
	*)
		echo "$1 is not a valid type of server I can set up";
		USAGE;
		;;
esac
