#!/usr/bin/php
<?php
require_once 'beercrush/oak.class.php';

$list=array();
$oak=new OAK;

$brewery_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/breweries'));
foreach ($brewery_list as $letter=>$breweries)
{
	foreach ($breweries as $brewery)
	{
		$list[]=array(
			'name' => $oak->remove_diacritics($brewery->name),
			'type' => 'brewery'
		);
	}
}

$beer_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/beers'));
foreach ($beer_list as $letter=>$beers)
{
	foreach ($beers as $beer)
	{
		$list[]=array(
			'name' => $oak->remove_diacritics($beer->name),
			'type' => 'beer'
		);
	}
}

$place_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/places'));
foreach ($place_list as $letter=>$places)
{
	foreach ($places as $place)
	{
		$list[]=array(
			'name' => $oak->remove_diacritics($place->name),
			'type' => 'place'
		);
	}
}

// var_dump($list);exit;
uasort($list,'cmp_function');

$last_item=array();
foreach ($list as $item)
{
	// Filter duplicates (array_unique() doesn't work correctly for arrays of arrays)
	if ($item!=$last_item)
		print $item['name']."\t".$item['type']."\n";
	$last_item=$item;
}


function cmp_function($a,$b)
{
	return strcasecmp($a['name'],$b['name']);
}

?>