#!/usr/bin/php
<?php
require_once 'beercrush/oak.class.php';

$list=array();
$oak=new OAK;

$brewery_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/breweries'));
foreach ($brewery_list as $letter=>$breweries)
{
	foreach ($breweries as $brewery)
	{
		$list[]=$oak->remove_diacritics($brewery->name);
	}
}

$beer_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/beers'));
foreach ($beer_list as $letter=>$beers)
{
	foreach ($beers as $beer)
	{
		$list[]=$oak->remove_diacritics($beer->name);
	}
}

$place_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/places'));
foreach ($place_list as $letter=>$places)
{
	foreach ($places as $place)
	{
		$list[]=$oak->remove_diacritics($place->name);
	}
}

// var_dump($list);exit;
uasort($list,'cmp_function');
$list=array_unique($list);

foreach ($list as $item)
{
	print $item."\n";
}


function cmp_function($a,$b)
{
	return strcasecmp($a,$b);
}

?>