#!/usr/bin/php
<?php
require_once 'beercrush/oak.class.php';

$list=array();
$oak=new OAK;

$brewery_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/breweries'));
foreach ($brewery_list as $letter=>$breweries)
{
	foreach ($breweries as $brewery)
	{
		$list[]=array('name' => $oak->remove_diacritics($brewery->name), 'id' => $brewery->id);
	}
}

$beer_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/beers'));
foreach ($beer_list as $letter=>$beers)
{
	foreach ($beers as $beer)
	{
		$list[]=array('name' => $oak->remove_diacritics($beer->name), 'id' => $beer->id);
	}
}

$place_list=json_decode(file_get_contents($oak->get_config_info()->api->base_uri.'/places'));
foreach ($place_list as $letter=>$places)
{
	foreach ($places as $place)
	{
		$list[]=array('name' => $oak->remove_diacritics($place->name), 'id' => $place->id);
	}
}

// var_dump($list);exit;
if (uasort($list,'cmp_function'))
{
	foreach ($list as $item)
	{
		print $item['name']."\t".$item['id']."\n";
	}
}

function cmp_function($a,$b)
{
	return strcasecmp($a['name'],$b['name']);
}

?>