#!/usr/bin/php
<?php
require_once('beercrush/beercrush.php');
require_once('OAK/listener.class.php');

$oaklistener=new OAKListener($BC->oak,$argv[1]);
$oaklistener->gimme_messages('message_callback');

function message_callback($oaklistener,$msg) {
	print json_encode($msg);
	print "\n";
}
?>