#!/usr/bin/php
<?php
require_once 'beercrush/oak.class.php';

$oak=new OAK;
$oak->log_ident('update_doc');

$msg=file_get_contents('php://stdin');
$obj=json_decode($msg);
$oak->log('user_id='.$obj->user_id.' docid='.$obj->docid.' old_rev='.$obj->old_rev.' new_rev='.$obj->new_rev);

// Determine the doc type and call the appropriate script
$parts=split(':',$obj->docid);
// Find the script for this onchange
$prog=$oak->get_file_location('BIN_DIR').'/onchange/'.$parts[0];

if (!is_executable($prog))
{
	$oak->log($prog.' is not executable, not running the processor for queue '.$queue->name);
}
else
{
	$oak->log('Running: '.escapeshellcmd($prog).' '.escapeshellarg($obj->docid));
	
	$r=exec(escapeshellcmd($prog).' '.escapeshellarg($obj->docid),$output,$return_var);

	foreach ($output as $line)
	{
		$oak->log($line);
	}
}

?>