#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

$oak=new OAK;
$result=new OAKDocument('');
if ($oak->get_view("place/gps_coords",&$result)===false)
	throw new Exception('Unable to get view');
	
$rows=array();
foreach ($result->rows as $row)
{
	$rows[]=$row;
}

// Sort by latitude
if (uasort($rows,'compare_lat'))
{
	foreach ($rows as $row)
	{
		print $row->value->lat.' '.$row->value->lon.' '.$row->id.' '.htmlentities($row->key)."\n";
	}
}

function compare_lat($a,$b)
{
	$diff=((float)$a->value->lat) - ((float)$b->value->lat);
	if ($diff < 0)
		return -1;
	else if ($diff > 0)
		return 1;
	return 0;
}

?>