#!/bin/bash

# NOTE: This is not used anymore, see scripts/misc/autocomplete_list instead

# --START INCRONTAB RULES--
#
# $DOC_DIR/meta/brewery/autocomplete_names.txt IN_DELETE
# $DOC_DIR/brewery/ IN_MODIFY
#
# --END INCRONTAB RULES--

. /etc/BeerCrush/BeerCrush.conf
. $APP_DIR/etc/utils.sh

CHANGED_DIR=$(dirname $1);
CHANGED_FILENAME=$(basename $1);
CHANGED_EXT=$(FILEEXT $1);

AUTOCOMPLETE_NAMES_FILE="$DOC_DIR/meta/brewery/autocomplete_names.txt";

if LOCK $AUTOCOMPLETE_NAMES_FILE; then

	if [ ! -s $AUTOCOMPLETE_NAMES_FILE ]; then
		xmlstarlet sel -t -m "/brewery" -v name -o "&#09;" -v "@id" $DOC_DIR/brewery/*.xml > $AUTOCOMPLETE_NAMES_FILE.new
		mv $AUTOCOMPLETE_NAMES_FILE.new $AUTOCOMPLETE_NAMES_FILE
	fi

	# Only update if the changed file is an XML file
	if [ $CHANGED_DIR == "$DOC_DIR/brewery" -a $CHANGED_EXT == "xml" ]; then
		xmlstarlet sel -t -m "/brewery" -v name -o "&#09;" -v "@id" $CHANGED_DIR/$CHANGED_FILENAME > $AUTOCOMPLETE_NAMES_FILE.new
		
		# TODO: Remove the line with the modified file's brewery_id, otherwise the old one will remain in the list if the name has changed.
		
		cat $AUTOCOMPLETE_NAMES_FILE >> $AUTOCOMPLETE_NAMES_FILE.new
		sort -u --ignore-case $AUTOCOMPLETE_NAMES_FILE.new > $AUTOCOMPLETE_NAMES_FILE.new2
		mv $AUTOCOMPLETE_NAMES_FILE.new2 $AUTOCOMPLETE_NAMES_FILE
		rm -f $AUTOCOMPLETE_NAMES_FILE.new $AUTOCOMPLETE_NAMES_FILE.new2
		N=$(wc -l $AUTOCOMPLETE_NAMES_FILE|awk '{print $1}');
		SYSLOG_INFO "Updated $AUTOCOMPLETE_NAMES_FILE ($N entries) with change to $CHANGED_DIR/$CHANGED_FILENAME";
	fi
	
else
	SYSLOG_ERROR "Unable to acquire lock -- $AUTOCOMPLETE_NAMES_FILE not updated by change to $CHANGED_DIR/$CHANGED_FILENAME";
fi
