#!/bin/sh
. /etc/BeerCrush/BeerCrush.conf

if [ -z "$1" ]; then
	echo "Usage: $0 <Brewery ID>";
	exit;
fi

# Get list of beers for brewery
$APP_DIR/scripts/brewery/beerlist "$1" | $APP_DIR/tools/json2xml | xmlstarlet sel -t -m "//doc/item" -v "@id" -n | sed -e '$d' |
while read BEER_ID; do
	echo $BEER_ID;
	$APP_DIR/src/onchange/beer "$BEER_ID"
done
