#!/usr/bin/php
<?php
require_once 'beercrush/beercrush.php';
require_once 'OAK/oak.class.php';

if (empty($argv[1])) {
	print "Usage: ".basename($argv[0])." <document_id> [<property>]\n";
	exit;
}

$property=null;
if (!empty($argv[2]))
	$property=$argv[2];
	
$setup=json_decode(file_get_contents(BeerCrush::SETUP_CONF));
$webapp=json_decode(file_get_contents(BeerCrush::CONF_FILE));

$docid=$argv[1];

// PHP
$url='http://'.$setup->servers->web->servers[0].'/'.str_replace(':','/',$docid);
output($url,"PHP      ($url):",$property);

// API
$url="{$webapp->api->base_uri}/".str_replace(':','/',$docid);
output($url,"API      ($url):",$property);

// DB Cache
$url="http://".$setup->servers->{'couchdb-proxy'}->servers[0]."/{$webapp->couchdb->database}/$docid";
output($url,"DB Cache ($url):",$property);

// Live DB
$url="http://{$setup->servers->couchdb->servers[0]}/beercrush/$docid";
output($url,"Live DB  ($url):",$property);

function get_http($url) {
	// print "URL:$url\n";
	$doc=null;
	$ch=curl_init($url);
	if ($ch) {
		curl_setopt($ch,CURLOPT_RETURNTRANSFER,TRUE);
		$doc=curl_exec($ch);
		curl_close($ch);
	}
	return $doc;
}

function output($url,$title,$param=null) {
	$doc=get_http($url);
	print $title;
	if ($doc) {
		$obj=json_decode($doc);
		if (is_null($param))
			print_r($obj);
		else
			print_r($obj->$param);
	}
	print "\n";
}

?>