#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

$config_file=null;
$dirname=null;

$opts=getopt('C:d:si:');

if (!empty($opts['C'])) {
	$config_file=$opts['C'];
}

$dirname=null;
if (!empty($opts['d'])) {
	$dirname=$opts['d'];
}

$create_subdirs=false;
if (isset($opts['s'])) {
	$create_subdirs=true;
}

$docid=null;
if (isset($opts['i'])) {
	if (!empty($opts['i'])) {
		$docid=$opts['i'];
	}
	else {
		print "-i requires a document ID\n";
		exit(1);
	}
}

if (empty($config_file)) {
	print <<<EOF
Usage: {$argv[0]} -C <conf file> [-d <directory> [-s]] [-i <document ID>]

	-C	Path to webapp.conf file (required)
	-d	Directory to put document files. If omitted, output is written to stdout. (optional)
	-s	Create subdirectories for documents based on document ID.
		The IDs are split at colons (:) and replaced with slashes (/). (optional)
	-i	Specify a document ID to dump. Otherwise, all documents are dumped. (optional)

EOF;
	exit(1);
}


$oak=new OAK($config_file);
$couchdb_nodes=$oak->get_config_info()->couchdb->nodes;
$dbname=$oak->get_config_info()->couchdb->database;

if (!is_null($docid)) {
	dump_doc($docid);
}
else { // Dump all docs
	$view=new stdClass;
	if ($oak->get_document('_all_docs',$view)!==TRUE) {
	}
	else {
		foreach ($view->rows as $row)
		{
			dump_doc($row->id);
		}
	}
}

function dump_doc($id) {
	global $oak;
	global $couchdb_nodes;
	global $dbname;
	global $create_subdirs;
	global $dirname;
	
	$ch=curl_init('http://'.$couchdb_nodes[rand()%count($couchdb_nodes)].'/'.$dbname.'/'.$id);
	if ($ch===FALSE)
	{
		print "Failed to get ".$id."\n";
	}
	else
	{
		curl_setopt($ch,CURLOPT_RETURNTRANSFER,TRUE);
		$answer=curl_exec($ch);
		$info=curl_getinfo($ch,CURLINFO_HTTP_CODE);
		if ($info!=200) {
			print "\n";
		}
		else {
			if (is_null($dirname)) {
				$docfilename="php://stdout";
			}
			else {
				// Create filename
				if ($create_subdirs)
					$docfilename=$dirname.'/'.str_replace(':','/',$id);
				else
					$docfilename=$dirname.'/'.$id;

				$d=dirname($docfilename);
				if (!file_exists($d)) {
					mkdir($d,0775,true);
				}
				
				print "$docfilename\n";
			}
			$doc=json_decode($answer);
			$docstr=$oak->jsontidy($doc);
			file_put_contents($docfilename,$docstr);
		}

		curl_close($ch);
	}
	
}
?>
