#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $(basename $0) <config file>";
	echo;
	exit;
fi

CONF_FILE=$1;

PATHS=$(php -r '$conf=json_decode(file_get_contents($argv[1]));print $conf->file_locations->APP_DIR." ".$conf->file_locations->LOCAL_DIR;' $CONF_FILE);
APP_DIR=$(echo $PATHS | awk '{print $1}');
LOCAL_DIR=$(echo $PATHS | awk '{print $2}');
GIT_DIR=$LOCAL_DIR/git;
BINDIR=/usr/local/beercrush/bin

$BINDIR/listen -p /var/run/BeerCrush/dbchanges2git.pid dbchanges |
	$BINDIR/jsonpath id rev oldrev couchdb.host couchdb.port couchdb.db |
	while read DOCID NEWREV OLDREV COUCHDB_HOST COUCHDB_PORT COUCHDB_DBNAME; do
		# Get the new doc into the git working tree
		$BINDIR/db_dump -C $1 -d $GIT_DIR -s -i $DOCID
		if [ $? -eq 0 ]; then
			# Commit it
			FNAME=$(echo $DOCID | sed -e 's/:/\//g');
			git --work-tree=$GIT_DIR --git-dir=$GIT_DIR/.git add $FNAME;
			git --work-tree=$GIT_DIR --git-dir=$GIT_DIR/.git commit -m 'Auto-commit by dbchanges2git' "$FNAME";
			echo Committed $FNAME;
		fi
		
done