#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

if ($argc<2)
	exit;
	
$oak=new OAK();
$jsonobj=new stdClass;
$rev=null;
if ($argv>2)
	$rev=$argv[2];
$oak->get_document($argv[1],$jsonobj,$rev);
print json_encode($jsonobj);

?>
