#!/bin/bash

QUIET=0;
ISTYPE=0;

while getopts "qt" opt; do
	case $opt in 
		q)
			QUIET=1;
			shift;
			;;
		t)
			for T in cgi couchdb couchdb-proxy gitrepo memcached mgmt php-cgi solr solr-proxy web; do
				if $0 -q $T; then
					echo $T
				fi
			done
			exit;
			;;
		\?)
			# echo "Invalid option: -$OPTARG" >&2
			exit;
			;;
	esac
done

case $1 in
	web) ;;
	mgmt) ;;
	solr) ;;
	php-cgi) ;;
	cgi) ;;
	couchdb) ;;
	gitrepo) ;;
	memcached) ;;
	couchdb-proxy) ;;
	solr-proxy) ;;
	*)
		cat - <<EOF
Unrecognized server type: $1

Recognized types:

	cgi             FastCGI server (not a PHP5 FastCGI server)
	couchdb         CouchDB database server
	couchdb-proxy   NGiNX server acting as a proxy to a CouchDB server
	gitrep          Git repository
	memcached       memcached server
	mgmt            management server
	php-cgi         PHP FastCGI server
	solr            Apache Solr search server
	solr-proxy      NGiNX server acting as a proxy to a Solr server
	web             NGiNX server acting as a proxy to the web site

EOF
		exit;
		;;
		
esac

# Get my IP(s)
MYIPS=$(/sbin/ifconfig |grep "inet addr:" | sed -e 's/ *inet  *addr:\([0-9\.]*\).*$/\1/');

SERVER_TYPE_IPS=$(cat /etc/BeerCrush/setup.conf | php -r '
$conf=json_decode(stream_get_contents(STDIN));
if (!is_null($conf)) {
	foreach ($conf->servers->{$argv[1]}->servers as $s) {
		list($ip,$port)=preg_split("/:/",$s);
		print "$ip ";
	}
}
' $1);

for S in $SERVER_TYPE_IPS; do
	SS=`dig $S +short`;
	# Some hosts return nothing when dig is used against it's IP address, so do this check first...
	if [ ! -z "$SS" ]; then S=$SS; fi
	for MY in $MYIPS; do
		if [ "$S" = "$MY" ]; then
			let ISTYPE=1;
		fi
	done
done

if [ $ISTYPE = 1 ]; then

	if [ $QUIET = 0 ]; then 
		echo "Yes"; 
	fi

	exit 0;
	
else

	if [ $QUIET = 0 ]; then
		echo "No"; 
	fi

	exit 1;
fi

