#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

if ($argc<3)
{
	print "Usage: $argv[0] <json property name> <docid>\n";
	exit;
}

$json=file_get_contents("php://stdin");
$orig_data=json_decode($json);

$oak=new OAK("/etc/BeerCrush/json.conf");
$doc=new stdClass;
$oak->get_document($argv[2],$doc);

$orig_data->$argv[1]=$doc;

print json_encode($orig_data);

?>