#!/usr/bin/php
<?php

function diff($a,$b,$prefix,&$changes)
{
	if (gettype($a)!=gettype($b))
	{
		print "Changed $prefix: ".json_encode($a).'->'.json_encode($b)."\n";
	}
	else if (is_scalar($a) && is_scalar($b))
	{
		if ($a!=$b)
		{
			$changes=array(
				'old' => $a,
				'new' => $b
			);
			print "-\"$prefix\": $a\n";
			print "+\"$prefix\": $b\n";
		}
	}
	else if (is_object($a))
	{
		// Get union of keys
		$all_keys=array();
		foreach ($a as $k=>$v)
		{
			$all_keys[]=$k;
		}
		foreach ($b as $k=>$v)
		{
			if (!in_array($k,$all_keys))
				$all_keys[]=$k;
		}

		if (!empty($prefix))
			$prefix.='.';

		foreach ($all_keys as $k)
		{
			if (!isset($b->$k))
			{
				$changes[$k]=array(
					'old' => $a->$k
				);
				// print "$prefix$k\t\t{$a->$k}\t\n";
				print "-\"$prefix$k\": ";print json_encode($a->$k);print "\n";
			}
			else if (!isset($a->$k))
			{
				$changes[$k]=array(
					'new' => $b->$k
				);
				print "+\"$prefix$k\": ";print json_encode($b->$k);print "\n";
			}
			else if ($a->$k!==$b->$k)
			{
				diff($a->$k,$b->$k,$prefix.$k,$changes[$k]);
			}
		}
	}
}

$filea=file_get_contents($argv[1]);
$fileb=file_get_contents($argv[2]);

if ($filea!==$fileb)
{
	$a=json_decode($filea);
	$b=json_decode($fileb);
	unset($a->_rev);
	unset($a->meta->mtime);
	unset($b->_rev);
	unset($b->meta->mtime);

	print "--- {$argv[1]}\n+++ {$argv[2]}\n\n";
	$changes=array();
	diff($a,$b,'',$changes);
	print "\n";
	// print json_encode($changes);
}

?>