#!/usr/bin/php
<?php
require_once('OAK/oak.class.php');

$oak=new OAK;

// Parse each line of stdin as a series of JSON objects
$input=fopen('php://stdin','r');
while (($line=fgets($input))!=null)
{
	// print $line;
	$new_document=json_decode($line);
	if (is_null($new_document))
		throw new Exception('Input not correct JSON format. Use output of the tools/getdesigndocs script.');

	$current_doc=new stdClass;
	$oak->get_document($new_document->_id,&$current_doc);

	$current_rev=$current_doc->_rev;
	unset($current_doc->_rev);
	unset($new_document->_rev);
	
	if ($current_doc==$new_document)
	{
		print "No change for {$new_document->_id}\n";
	}
	else
	{
		print "Updating {$new_document->_id}\n";
		$new_document->_rev=$current_rev;
		$oak->put_document($new_document->_id,$new_document);
	}
}
fclose($input);

?>
