#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

if ($argc<2)
{
	print "Usage: argv[1] <docid>\n";
	exit;
}
	
$doc=file_get_contents("php://stdin");

$oak=new OAK;
if ($oak->put_document($argv[1],$doc)===false)
	return 1;
return 0;

?>
