#!/usr/bin/php
<?php
require_once('beercrush/oak.class.php');

if ($argc<2)
{
	print "Usage: argv[1] <docid>\n";
	exit;
}
	
$conf_file="/etc/BeerCrush/json.conf";

$doc=file_get_contents("php://stdin");

$oak=new OAK();
if ($oak->put_document_json($argv[1],$doc))
	return 1;
return 0;

?>