<?php
include('header.php');
?>
<h1>Privacy Policy</h1>
<div id="page_privacy">
<p>At Beer Crush we recognize that privacy is important. This Privacy Policy applies to all of the products, services and websites offered by Beer Crush or its subsidiaries or affiliated companies; collectively, Beer Crush's "services." In addition, where more detailed information is needed to explain our privacy practices, we post supplementary privacy notices to describe how particular services process personal information.</p>

<p>Beer Crush adheres to the US Safe Harbor Privacy Principles of Notice, Choice, Onward Transfer, Security, Data Integrity, Access and Enforcement, and is registered with the <a href="http://www.export.gov/safeharbor/" rel="nofollow">U.S. Department of Commerce's Safe Harbor Program</a>.
    </p><p>If you have any questions about this Privacy Policy, please feel free to <a href="/contact">contact us</a> through our website or write to us at
    </p>
    <blockquote><address>Privacy Matters<br>c/o Beer Crush<br>P.O. Box 2941<br>Vashon, Washington 98070<br>USA</address></blockquote>
    <h3 id="information">Information we collect and how we use it</h3>
    <p>We offer a number of services that do not require you to register for an account or provide any personal information to us, such as Beer Crush Search. In order to provide our full range of services, we may collect the following types of information:
    </p><ul>
      <li><strong>Information you provide</strong> &ndash; When you sign up for a Beer Crush Account or other Beer Crush service or promotion that requires registration, we ask you for personal information (such as your name, email address and an account password). For certain services, such as our advertising programs, we also request credit card or other payment account information which we maintain in encrypted form on secure servers. We may combine the information you submit under your account with information from other Beer Crush services or third parties in order to provide you with a better experience and to improve the quality of our services. For certain services, we may give you the opportunity to opt out of combining such information.
      </li><li><strong>Cookies</strong> &ndash; When you visit Beer Crush, we send one or more cookies &ndash; a small file containing a string of characters &ndash; to your computer or other device that uniquely identifies your browser. We use cookies to improve the quality of our service, including for storing user preferences, improving search results and ad selection, and tracking user trends, such as how people search. Beer Crush also uses cookies in its advertising services to help advertisers and publishers serve and manage ads across the web. We may set one or more cookies in your browser when you visit a website, including Beer Crush sites that use our advertising cookies, and view or click on an ad supported by Beer Crush's advertising services.
      </li><li><strong>Log information</strong> &ndash; When you access Beer Crush services, our servers automatically record information that your browser sends whenever you visit a website. These server logs may include information such as your web request, Internet Protocol address, browser type, browser language, the date and time of your request and one or more cookies that may uniquely identify your browser.
      </li><li><strong>User communications</strong> &ndash; When you send email or other communications to Beer Crush, we may retain those communications in order to process your inquiries, respond to your requests and improve our services.
      </li><li><strong>Affiliated Beer Crush Services on other sites</strong> &ndash; We offer some of our services on or through other web sites. Personal information that you provide to those sites may be sent to Beer Crush in order to deliver the service. We process such information under this Privacy Policy. The affiliated sites through which our services are offered may have different privacy practices and we encourage you to read their privacy policies.
      </li><li><strong>Gadgets</strong> &ndash; Beer Crush may make available third party applications through its services. The information collected by Beer Crush when you enable a gadget or other application is processed under this Privacy Policy.&nbsp;Information collected by the application or gadget provider is governed by their privacy policies.
      </li><li><strong>Location data</strong> &ndash; Beer Crush offers location-enabled services, such as finding beer places nearby. If you use those services, Beer Crush may receive information about your actual location (such as GPS signals sent by a mobile device) or information that can be used to approximate a location (such as a cell ID, or geolocation information from the browser).
      </li><li><strong>Links</strong> &ndash; Beer Crush may present links in a format that enables us to keep track of whether these links have been followed. We use this information to improve the quality of our technology, customized content and advertising.       </li><li><strong>Other sites</strong> &ndash; This Privacy Policy applies to Beer Crush services only. We do not exercise control over the sites displayed as search results, sites that include Beer Crush applications, products or services, or links from within our various services. These other sites may place their own cookies or other files on your computer, collect data or solicit personal information from you.
    </li></ul>
    <p>Beer Crush only processes personal information for the purposes described in this Privacy Policy and/or the supplementary privacy notices for specific services. In addition to the above, such purposes include:
    </p><ul>
      <li>Providing our services, including the display of customized content and advertising;
      </li><li>Auditing, research and analysis in order to maintain, protect and improve our services;
      </li><li>Ensuring the technical functioning of our network;
      </li><li>Protecting the rights or property of Beer Crush or our users; and
      </li><li>Developing new services.
    </li></ul>
    <p>Beer Crush processes personal information on our servers in the United States of America and in other countries. In some cases, we process personal information on a server outside your own country. We may process personal information to provide our own services. In some cases, we may process personal information on behalf of and according to the instructions of a third party, such as our advertising partners.
    </p><h3 id="infochoices">Choices for personal information</h3>
    <p>When you sign up for a particular service that requires registration, we ask you to provide personal information. If we use this information in a manner different than the purpose for which it was collected, then we will ask for your consent prior to such use.
    </p><p>If we propose to use personal information for any purposes other than those described in this Privacy Policy and/or in the specific service privacy notices, we will offer you an effective way to opt out of the use of personal information for those other purposes. We will not collect or use sensitive information for purposes other than those described in this Privacy Policy and/or in the supplementary service privacy notices, unless we have obtained your prior consent.
    </p><p>Most browsers are initially set up to accept cookies, but you can reset your browser to refuse all cookies or to indicate when a cookie is being sent. However, some Beer Crush features and services may not function properly if your cookies are disabled.
    </p><p>You can decline to submit personal information to any of our services, in which case Beer Crush may not be able to provide those services to you.
    </p><h3 id="infosharing">Information sharing</h3>
    <p>Beer Crush only shares personal information with other companies or individuals outside of Beer Crush in the following limited circumstances:
    </p><ul>
      <li>We have your consent. We require opt-in consent for the sharing of any sensitive personal information.
      </li><li>We provide such information to our subsidiaries, affiliated companies or other trusted businesses or persons for the purpose of processing personal information on our behalf. We require that these parties agree to process such information based on our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality and security measures.
      </li><li>We have a good faith belief that access, use, preservation or disclosure of such information is reasonably necessary to (a) satisfy any applicable law, regulation, legal process or enforceable governmental request, (b) enforce applicable Terms of Service, including investigation of potential violations thereof, (c) detect, prevent, or otherwise address fraud, security or technical issues, or (d) protect against harm to the rights, property or safety of Beer Crush, its users or the public as required or permitted by law.
    </li></ul>
    <p>If Beer Crush becomes involved in a merger, acquisition, or any form of sale of some or all of its assets, we will ensure the confidentiality of any personal information involved in such transactions and provide notice before personal information is transferred and becomes subject to a different privacy policy.
    </p><p>We may share with third parties certain pieces of <a href="privacy_faq.html#toc-terms-aggregated-info">aggregated, non-personal information</a>, such as the number of users who searched for a particular term, for example, or how many users clicked on a particular advertisement. Such information does not identify you individually.
    </p><p>Please contact us at the address below for any additional questions about the management or use of personal data.
    </p><h3 id="infosecurity">Information security</h3>
    <p>We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include internal reviews of our data collection, storage and processing practices and security measures, as well as physical security measures to guard against unauthorized access to systems where we store personal data.
    </p><p>We restrict access to personal information to Beer Crush employees, contractors and agents who need to know that information in order to operate, develop or improve our services. These individuals are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution, if they fail to meet these obligations.
    </p><h3 id="dataintegrity">Data integrity</h3>
    <p>Beer Crush processes personal information only for the purposes for which it was collected and in accordance with this Privacy Policy or any applicable service-specific privacy notice. We review our data collection, storage and processing practices to ensure that we only collect, store and process the personal information needed to provide or improve our services or as otherwise permitted under this Policy. We take reasonable steps to ensure that the personal information we process is accurate, complete, and current, but we depend on our users to update or correct their personal information whenever necessary.
    </p><h3 id="access">Accessing and updating personal information</h3>
    <p>When you use Beer Crush services, we make good faith efforts to provide you with access to your personal information and either to correct this data if it is inaccurate or to delete such data at your request if it is not otherwise required to be retained by law or for legitimate business purposes. We ask individual users to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup tapes), or for which access is not otherwise required. In any case where we provide information access and correction, we perform this service free of charge, except if doing so would require a disproportionate effort. Some of our services have different procedures to access, correct or delete users' personal information. We provide the details for these procedures in the specific privacy notices or FAQs for these services.
    </p><h3 id="enforcement">Enforcement</h3>
    <p>Beer Crush regularly reviews its compliance with this Privacy Policy. Please feel free to direct any questions or concerns regarding this Privacy Policy or Beer Crush's treatment of personal information by <a href="/support/bin/request.py?form_type=user&amp;stage=fm&amp;user_type=user&amp;contact_type=privacy&amp;hl=en">contacting us</a> through this web site or by writing to us at
    </p>
    <blockquote><address>Privacy Matters<br>c/o Beer Crush<br>P.O. Box 2941<br>Vashon, Washington 98070<br>USA</address></blockquote>
    <p>When we receive formal written complaints at this address, it is Beer Crush's policy to contact the complaining user regarding his or her concerns. We will cooperate with the appropriate regulatory authorities, including local data protection authorities, to resolve any complaints regarding the transfer of personal data that cannot be resolved between Beer Crush and an individual.
    </p><h3 id="policychanges">Changes to this Privacy Policy</h3>
    <p>Please note that this Privacy Policy may change from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent, and we expect most such changes will be minor. Regardless, we will post any Privacy Policy changes on this page and, if the changes are significant, we will provide a more prominent notice (including, for certain services, email notification of Privacy Policy changes). Each version of this Privacy Policy will be identified at the top of the page by its effective date, and we will also keep <a href="privacy_archive.html">prior versions</a> of this Privacy Policy in an archive for your review.
    </p><p>If you have any additional questions or concerns about this Privacy Policy, please feel free to contact us any time through this web site or at
    </p>
    <blockquote><address>Privacy Matters<br>c/o Beer Crush<br>P.O. Box 2941<br>Vashon, Washington 98070<br>USA</address></blockquote>

</div>

<?php
include('footer.php');
?>