#!/usr/bin/php
<?php
require_once('OAK/jobs.class.php');

$opts=getopt('ocC:h');

if (isset($opts['h'])) {
	$cmdname=basename($argv[0]);
	print <<<EOF
Usage: $cmdname [-o] [-c] -C <conf file>

	-o Output log messages to stdout
	-c Use color in output
	-C Specify path to .conf file


EOF;
	exit;
}

$bOutput=isset($opts['o']);
$bColorOutput=isset($opts['c']);

try {
	$oak=new OAK($opts['C']);
}
catch (Exception $x) {
	print $x->getMessage()."\n";
	exit;
}

$oakjobs=new OAKJobs($oak,'oaklog');
$oakjobs->set_message_callback('log_message');
$oakjobs->gimme_jobs('log_job');

function log_job($oakjobs,$msg) {
	// Send ERRs and CRITs to somewhere where they'll be seen
	list($priority,$ident,$logmsg)=preg_split('/:/',$msg,3);
	if ($priority=='CRIT' || $priority=='ERR') {
		// TODO: If on a production server, send email to email address in config
	}

	$oakjobs->job_done($msg);
}

function log_message($oakjobs,$msg) {
	global $bOutput;
	global $bColorOutput;
	
	if ($bOutput) {
		// Parse message
		list($priority,$ident,$logmsg)=preg_split('/:/',$msg,3);
		if ($bColorOutput) {
			// See man console_codes for console escape codes
			if ($priority=='CRIT')
				print "\7\033[37;41m"; // Bell w/ white on red
			else if ($priority=='ERR')
				print "\033[31m"; // Red on white
			else
				print "\033[32m"; // Green on white
		}
		
		print $priority.' '.date('Y-m-d H:i:s').' '.$ident.' '.$logmsg."\n";
		
		if ($bColorOutput) {
			print "\033[0m";
		}
	}
}
?>